name: Visual C++

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        arch:
          - x64
          - x86
        tclbranch:
          - core-8-6-13
          - main
    env:
      TCLSUBDIR: ${{ matrix.arch }}-${{ matrix.tclbranch }}
      TCLDIR: C:/tcl/msvc/${{ matrix.arch }}-${{ matrix.tclbranch }}
    steps:
    # Note msvc defaults to 64-bit
    - name: Init MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}

    - name: Checkout iocp
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Cache Tcl build
      id: tcl-msvc-cache
      uses: actions/cache@v4
      with:
        path: ${{ env.TCLDIR }}
        key: ${{ runner.os }}-tcl-msvc-${{ env.TCLSUBDIR }}

    - name: Checkout Tcl
      if: steps.tcl-msvc-cache.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: tcltk/tcl
        ref: ${{ matrix.tclbranch }}
        path: tcl-${{ matrix.tclbranch }}

    - name: Build Tcl
      if: steps.tcl-msvc-cache.outputs.cache-hit != 'true'
      working-directory: tcl-${{ matrix.tclbranch }}/win
      shell: cmd
      run: |
        nmake /f makefile.vc INSTALLDIR=${{ env.TCLDIR }}
        nmake /f makefile.vc INSTALLDIR=${{ env.TCLDIR }} install

    - name: Make
      shell: cmd
      run: |
        cd win
        nmake /f makefile.vc INSTALLDIR=${{ env.TCLDIR }} realclean
        nmake /f makefile.vc INSTALLDIR=${{ env.TCLDIR }}

    - name: Test
      shell: cmd
      run: |
        cd win
        nmake /f makefile.vc INSTALLDIR=${{ env.TCLDIR }} test


